language: java
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
- bash docker_push
services:
- docker
env:
  global:
  - secure: kozPYK35suUHoLN+sDAbJ/ReyV7bgew6jbvL2MEAvX0yMLAoMVqJOWDgd+Jc3w8kKuIwJDyruKCKc7dFsLU7GZGvonr08BZTWEbeYRyUoWF/BvOBoDq3+spd4cQ2a5VXa0xzqNu1QUuA5D6ororxuWfFGTFeyOy4SEUsRBSPoIfU8HIikcRV2MvvgY82a2j8KhCbbtxOP75PqJygkdMKYGitBonr1CJVArHbSrxhb2XvHWj0VSE8B7m+O2UJLZBlOPriqvQZaudmdhi8btk6XaBe6amVFMoDGWDt+Uwkqfa2RRh2FJelgzGV9kfIdn5Qh0dopFNjoACFP54vbBauyB99sP6gA7Zxul71Dh+nuHYVtp8xgZ65mbkiLgQno3dOptgfnoEtvBZq0qALXbvxmjfaHDxFkWlfXd6NC1F7e2n2U96F2uTAyAEtTbwFz5YCrPqCIW6Ln33x0L4qOBCmdkzhfDctHqTJ4hbAbZMTk32KAJNfXpEUawhMp9QnpWzaWUZHyxTrsGa7MTkl8KuFUY7k44WHhy6p84nlmPbSCxHZlLmeA9nCf4Anubs11SHpMBmw5DG8EgL+CA1kX/5AgKnpUgIXzOG2JEBH2iuJt7gwlZo8c8+CLaRSj9ENTDlosQAGdOk5QJ0S32ToFVGqo3vQXkWiUSPGby+nzyqL9fI=
  - secure: B9NpjVFKEd3Za3l07akwx9qD6hccrARl8PxwDX35uXroJCvJDxtbcshA28Dg9yn2WAO1il1n8N6atlLInhmSvqQk0RXQDsjXKNBRMUdnXT5eOSwuLvnH0FrNBNNGLXhF/f/nQTjH0KiR7JH5oL2Wu6g6ylx7NXbYwnkKXjHD1Wp5yIGQozA5NGd5GkXz+XkMOU4lgvYuvyNFEajC9d9EkrFQmpwBnamXo+kZP97jvA3/jHc2jP1tFRmBWxvN4c5rtrblf/pu5rYX3DDWaojBDwJMl7BzNe0i5/MEv+QLVkCEvq8U6syxqNFn4MFEZ1ydxJhJyOdcMK/oE6bO5nZ3DoNBsnV+y37dzj3dJlPQOR3A/bBTMx7hYRBdl3zr2tjIVjApZkvfuf7wW5lrA5Si/L5LFgAAkfcv2FvbaQBaIqXxkejnES7oLFBVEnjv66+6K9DgnCE46tk1HPcoHXvs+dIxbj6fDfMuLenOE6oLNNlcSA894oCzLv5r4ThoJ4wgoE/Se6jAZ5gnRHQS4/XaYYu1YzAIX/9QS78g9roKqmulOxX9+uTz0edlbM4hEPN7JIOC9M2SAvLJ31+DNpbMYOKou8kFkVdd8gCVeTWMTykSKDO7EZgSppPdyFEMBXJLXyhofKfBV747LNN3wmtdE2y2nKjmEAQa70lRGOooxa0=
