language: java
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
services:
- docker
script:
- bash docker_push
env:
  global:
    secure: lZZYfcfDc0C5qT6HJqWqfw+L3uBeW2XUBRVBGoGEOENWnQ/BGRy9Zo9Gehk4lWZjz3dQzZ9tKyVfz5v7Ec7YyIJY+B7ul9GNkr5pGorM6UR4LL9KPExrkZdeKO/TUNRcMmQa2NyEs/9LRsWWRmUvHxWrUp7lf6rIuDGOi4Lg3bAzpWotGA4xrChVFo9xrCBqTGg6HKUgTVY2fL8lUfC9foCs+09ipbPgBm9l7SDJUCrSTzC4gpVFULogpfPybOifm9Px5kTH12dPb1yga+d67el2JFZCJo53mGgNNdK/WMjkbnZ4zeSHP1iEfyZpKvSwePhnhIqBTVuyKbcpxiCL3oym+MpLXp2sS+iOavJxJ7Eu6K/8XMumW7Uz2sDy4Fz6JwbufocaR0YnFf9IFkSeJm/ICuatIxVnlfCmZojPxqu/pT9BoHjvxpHqfSZgdGaUWVEX+Uz6KfWCU3IUHKC2rpKnNuMDTy9rDtIIBOgXfujkj/fVPPn+D2IfES6gzgSR4TOMvkdcDCiLvfXjEqHymHaSHUxxDLLnDwZ2BeAC13A7CKQWMth2rI87LertoBtrCNe4NdNTQPvm+07Eh0VfNZMG/py0LJ9RSU9X8yHRCPZKzyTBuZpH+dvGa04d80mOMc9rlvMDxw9ewbXLrpV/RJfhOMOfJLvtGNAxwtpd6Rs=
